export const mockData = {
  content: [
    {
      id: '611',
      arangoId: 'Cenotes/611',
      name: 'X-Tukil',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.85_1',
        name_2: 'Temozón',
        varname_2: 'Temozon',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.TN',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'CENOTE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -88.180833,
          y: 20.839444,
          type: 'Point',
          coordinates: [-88.180833, 20.839444],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '2063',
      arangoId: 'Cenotes/2063',
      name: 'Santa Ines ll',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.96_1',
        name_2: 'Tizimín',
        varname_2: '',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.TW',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'NO_TYPE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -88.269072,
          y: 21.279166,
          type: 'Point',
          coordinates: [-88.269072, 21.279166],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '1934',
      arangoId: 'Cenotes/1934',
      name: 'Chen Kin',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.57_1',
        name_2: 'Panabá',
        varname_2: 'Panaba',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.PA',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'NO_TYPE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -88.380594,
          y: 21.345252,
          type: 'Point',
          coordinates: [-88.380594, 21.345252],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '2001',
      arangoId: 'Cenotes/2001',
      name: 'Cenote 2',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.96_1',
        name_2: 'Tizimín',
        varname_2: '',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.TW',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'CENOTE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -87.936766,
          y: 21.236388,
          type: 'Point',
          coordinates: [-87.936766, 21.236388],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '1050',
      arangoId: 'Cenotes/1050',
      name: 'Xuneb',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.16_1',
        name_2: 'Chemax',
        varname_2: '',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.CX',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'NO_TYPE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -88.008055,
          y: 20.701388,
          type: 'Point',
          coordinates: [-88.008055, 20.701388],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '1736',
      arangoId: 'Cenotes/1736',
      name: 'Ochil (Gruta)',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.36_1',
        name_2: 'Homún',
        varname_2: 'Homun',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.HM',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'DRY_CAVE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -89.276027,
          y: 20.7425,
          type: 'Point',
          coordinates: [-89.276027, 20.7425],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '1356',
      arangoId: 'Cenotes/1356',
      name: 'Izmal-chen',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.76_1',
        name_2: 'Tecoh',
        varname_2: '',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.TC',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'NO_TYPE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -89.44373,
          y: 20.647694,
          type: 'Point',
          coordinates: [-89.44373, 20.647694],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '1233',
      arangoId: 'Cenotes/1233',
      name: 'Kambul',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.50_1',
        name_2: 'Mérida',
        varname_2: 'Merida',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.MR',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'NO_TYPE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 7, rating: 4.714286 },
      geojson: {
        geometry: {
          x: -89.720972,
          y: 21.073666,
          type: 'Point',
          coordinates: [-89.720972, 21.073666],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '515',
      arangoId: 'Cenotes/515',
      name: 'Xhasil',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.23_1',
        name_1: 'Quintana Roo',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.23.2_1',
        name_2: 'Cozumel',
        varname_2: '',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.QR.CO',
      },
      createdAt: '2019-06-27T00:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'CENOTE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -87.79,
          y: 20.536111,
          type: 'Point',
          coordinates: [-87.79, 20.536111],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '1604',
      arangoId: 'Cenotes/1604',
      name: 'San Miguel',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.96_1',
        name_2: 'Tizimín',
        varname_2: '',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.TW',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'NO_TYPE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -87.879166,
          y: 21.165833,
          type: 'Point',
          coordinates: [-87.879166, 21.165833],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '718',
      arangoId: 'Cenotes/718',
      name: 'San Loren',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.96_1',
        name_2: 'Tizimín',
        varname_2: '',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.TW',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'CENOTE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -87.901944,
          y: 21.010556,
          type: 'Point',
          coordinates: [-87.901944, 21.010556],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '746',
      arangoId: 'Cenotes/746',
      name: 'Yokdzonot',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.96_1',
        name_2: 'Tizimín',
        varname_2: '',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.TW',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'CENOTE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -88.217778,
          y: 21.244167,
          type: 'Point',
          coordinates: [-88.217778, 21.244167],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '610',
      arangoId: 'Cenotes/610',
      name: 'X-Makulan',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.85_1',
        name_2: 'Temozón',
        varname_2: 'Temozon',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.TN',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'CENOTE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -88.160278,
          y: 20.92,
          type: 'Point',
          coordinates: [-88.160278, 20.92],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '709',
      arangoId: 'Cenotes/709',
      name: 'Sajkanche',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.96_1',
        name_2: 'Tizimín',
        varname_2: '',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.TW',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'CENOTE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -87.563889,
          y: 21.034167,
          type: 'Point',
          coordinates: [-87.563889, 21.034167],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '845',
      arangoId: 'Cenotes/845',
      name: 'Kan ha',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.6_1',
        name_2: 'Buctzotz',
        varname_2: '',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.BU',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'NO_TYPE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -88.706111,
          y: 21.24,
          type: 'Point',
          coordinates: [-88.706111, 21.24],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '1907',
      arangoId: 'Cenotes/1907',
      name: 'Áaktun U Xa',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.98_1',
        name_2: 'Tzucacab',
        varname_2: '',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.TZ',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'DRY_CAVE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -89.143455,
          y: 20.094325,
          type: 'Point',
          coordinates: [-89.143455, 20.094325],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '137',
      arangoId: 'Cenotes/137',
      name: 'Rancho girasol 2',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.101_1',
        name_2: 'Umán',
        varname_2: 'Uman',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.UM',
      },
      createdAt: '2017-10-03T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'CENOTE',
      issues: [],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -89.814229,
          y: 20.755115,
          type: 'Point',
          coordinates: [-89.814229, 20.755115],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '1488',
      arangoId: 'Cenotes/1488',
      name: 'X tres',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.86_1',
        name_2: 'Tepakán',
        varname_2: '',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.TB',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'NO_TYPE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -89.039166,
          y: 21.082222,
          type: 'Point',
          coordinates: [-89.039166, 21.082222],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '1869',
      arangoId: 'Cenotes/1869',
      name: 'San Cayetano',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.96_1',
        name_2: 'Tizimín',
        varname_2: '',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.TW',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'NO_TYPE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -87.68825,
          y: 21.239722,
          type: 'Point',
          coordinates: [-87.68825, 21.239722],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '191',
      arangoId: 'Cenotes/191',
      name: 'Kanha',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.6_1',
        name_2: 'Buctzotz',
        varname_2: '',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.BU',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'CENOTE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -88.695556,
          y: 21.297778,
          type: 'Point',
          coordinates: [-88.695556, 21.297778],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '1697',
      arangoId: 'Cenotes/1697',
      name: 'X',
      touristic: true,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.102_1',
        name_2: 'Valladolid',
        varname_2: '',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.VA',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'WATER_WELL',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 55, rating: 4.8727274 },
      geojson: {
        geometry: {
          x: -88.056944,
          y: 20.685277,
          type: 'Point',
          coordinates: [-88.056944, 20.685277],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '2047',
      arangoId: 'Cenotes/2047',
      name: 'Anás',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.76_1',
        name_2: 'Tecoh',
        varname_2: '',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.TC',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'NO_TYPE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -89.42919,
          y: 20.612563,
          type: 'Point',
          coordinates: [-89.42919, 20.612563],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '236',
      arangoId: 'Cenotes/236',
      name: 'Xcosil',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.14_1',
        name_2: 'Chankom',
        varname_2: '',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.CM',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'CENOTE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -88.519167,
          y: 20.556944,
          type: 'Point',
          coordinates: [-88.519167, 20.556944],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '346',
      arangoId: 'Cenotes/346',
      name: 'Boxdzonot',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.29_1',
        name_2: 'Dzilam González',
        varname_2: 'Dzilam Gonzalez',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.DG',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'CENOTE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -88.705,
          y: 21.343056,
          type: 'Point',
          coordinates: [-88.705, 21.343056],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '1119',
      arangoId: 'Cenotes/1119',
      name: 'Sac bake kan',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.91_1',
        name_2: 'Tinúm',
        varname_2: '',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.TI',
      },
      createdAt: '2019-06-27T00:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'NO_TYPE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -88.586111,
          y: 20.789166,
          type: 'Point',
          coordinates: [-88.586111, 20.789166],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '64',
      arangoId: 'Cenotes/64',
      name: 'Pixton',
      touristic: true,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.65_1',
        name_2: 'Sanahcat',
        varname_2: '',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.SA',
      },
      createdAt: '2016-05-07T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'CENOTE',
      issues: [],
      alternativeNames: [],
      social: { totalComments: 14, rating: 0.0 },
      geojson: {
        geometry: {
          x: -89.2189722222,
          y: 20.7697777778,
          type: 'Point',
          coordinates: [-89.2189722222, 20.7697777778],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '1626',
      arangoId: 'Cenotes/1626',
      name: 'Yok kat',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.96_1',
        name_2: 'Tizimín',
        varname_2: '',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.TW',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'NO_TYPE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -87.826944,
          y: 21.045833,
          type: 'Point',
          coordinates: [-87.826944, 21.045833],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '1094',
      arangoId: 'Cenotes/1094',
      name: 'Esperanza(Aguada)',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.29_1',
        name_2: 'Dzilam González',
        varname_2: 'Dzilam Gonzalez',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.DG',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'WATERY',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -88.888333,
          y: 21.313611,
          type: 'Point',
          coordinates: [-88.888333, 21.313611],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '1779',
      arangoId: 'Cenotes/1779',
      name: 'Cascabel (Sta Barbara)',
      touristic: true,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.36_1',
        name_2: 'Homún',
        varname_2: 'Homun',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.HM',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'NO_TYPE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -89.303055,
          y: 20.724444,
          type: 'Point',
          coordinates: [-89.303055, 20.724444],
        },
        type: 'Feature',
        properties: {},
      },
    },
    {
      id: '747',
      arangoId: 'Cenotes/747',
      name: 'Yokdzonot',
      touristic: false,
      gadm: {
        gid_0: 'MEX',
        name_0: 'Mexico',
        gid_1: 'MEX.31_1',
        name_1: 'Yucatán',
        varname_1: null,
        nl_NAME_1: '',
        type_1: null,
        engtype_1: null,
        cc_1: null,
        hasc_1: null,
        gid_2: 'MEX.31.96_1',
        name_2: 'Tizimín',
        varname_2: '',
        nl_NAME_2: '',
        type_2: 'Municipio',
        engtype_2: 'Municipality',
        cc_2: '',
        hasc_2: 'MX.YU.TW',
      },
      createdAt: '2019-06-27T06:00:00.000+00:00',
      updatedAt: '2021-05-16T23:59:17.680+00:00',
      type: 'CENOTE',
      issues: ['GEOTAG_NOT_VERIFIED'],
      alternativeNames: [],
      social: { totalComments: 0, rating: 0.0 },
      geojson: {
        geometry: {
          x: -87.900833,
          y: 21.016667,
          type: 'Point',
          coordinates: [-87.900833, 21.016667],
        },
        type: 'Feature',
        properties: {},
      },
    },
  ],
  pageable: {
    sort: { empty: true, sorted: false, unsorted: true },
    offset: 0,
    pageNumber: 0,
    pageSize: 30,
    unpaged: false,
    paged: true,
  },
  last: false,
  totalPages: 70,
  totalElements: 2073,
  size: 30,
  number: 0,
  sort: { empty: true, sorted: false, unsorted: true },
  first: true,
  numberOfElements: 30,
  empty: false,
};

export const mockVariables = {
  content: [
    {
      id: 'benzene',
      arangoId: 'Variables/benzene',
      name: 'Benzene',
      description: 'Amount of Benzene in cenote water',
      units: 'mu g/L',
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.082+00:00',
      type: 'NUMBER_WITH_UNITS',
      enumValues: null,
      accessLevel: 'SENSITIVE',
      theme: 'WATER',
      origin: 'OFFICE',
    },
    {
      id: 'benzoAnthracene',
      arangoId: 'Variables/benzoAnthracene',
      name: 'Benzo (a) anthracene',
      description: 'Amount of Benzo (a) anthracene in cenote water',
      units: 'mu g/L',
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.084+00:00',
      type: 'NUMBER_WITH_UNITS',
      enumValues: null,
      accessLevel: 'SENSITIVE',
      theme: 'WATER',
      origin: 'OFFICE',
    },
    {
      id: 'benzoFluoranthene',
      arangoId: 'Variables/benzoFluoranthene',
      name: 'Benzo (b) fluoranthene',
      description: 'Amount of Benzo (b) fluoranthene in cenote water',
      units: 'mu g/L',
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.087+00:00',
      type: 'NUMBER_WITH_UNITS',
      enumValues: null,
      accessLevel: 'SENSITIVE',
      theme: 'WATER',
      origin: 'OFFICE',
    },
    {
      id: 'benzoPerylene',
      arangoId: 'Variables/benzoPerylene',
      name: 'Benzo (g, h, i) perylene',
      description: 'Amount of Benzo (g, h, i) perylene in cenote water',
      units: 'mu g/L',
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.090+00:00',
      type: 'NUMBER_WITH_UNITS',
      enumValues: null,
      accessLevel: 'SENSITIVE',
      theme: 'WATER',
      origin: 'OFFICE',
    },
    {
      id: 'benzoPyrene',
      arangoId: 'Variables/benzoPyrene',
      name: 'Benzo (a) pyrene',
      description: 'Amount of Benzo (a) pyrene in cenote water',
      units: 'mu g/L',
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.093+00:00',
      type: 'NUMBER_WITH_UNITS',
      enumValues: null,
      accessLevel: 'SENSITIVE',
      theme: 'WATER',
      origin: 'OFFICE',
    },
    {
      id: 'billing',
      arangoId: 'Variables/billing',
      name: 'Billing',
      description: 'Possibility of formal billing',
      units: null,
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.096+00:00',
      type: 'BOOLEAN',
      enumValues: null,
      accessLevel: 'PRIVATE',
      theme: 'TOURISM',
      origin: 'FIELD',
    },
    {
      id: 'birdWatching',
      arangoId: 'Variables/birdWatching',
      name: 'Guided bird watching',
      description: 'Specialized service for local bird watching through',
      units: null,
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.099+00:00',
      type: 'BOOLEAN',
      enumValues: null,
      accessLevel: 'PUBLIC',
      theme: 'TOURISM',
      origin: 'FIELD',
    },
    {
      id: 'boxOffice',
      arangoId: 'Variables/boxOffice',
      name: 'Ticket office',
      description: 'Cabin or specific site for entrance fees',
      units: null,
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.101+00:00',
      type: 'BOOLEAN',
      enumValues: null,
      accessLevel: 'PUBLIC',
      theme: 'ORGANIZATION',
      origin: 'FIELD',
    },
    {
      id: 'btex',
      arangoId: 'Variables/btex',
      name: 'BTEX (Volatile hydrocarbons)',
      description: 'Amount of BTEX (Volatile hydrocarbons) in cenote water',
      units: 'mu g/L',
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.104+00:00',
      type: 'NUMBER_WITH_UNITS',
      enumValues: null,
      accessLevel: 'SENSITIVE',
      theme: 'WATER',
      origin: 'OFFICE',
    },
    {
      id: 'busEntrance',
      arangoId: 'Variables/busEntrance',
      name: 'Bus entrance',
      description: 'Capacity to receive buses in the cenote',
      units: null,
      timeseries: false,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.106+00:00',
      type: 'BOOLEAN',
      enumValues: null,
      accessLevel: 'PUBLIC',
      theme: 'ORGANIZATION',
      origin: 'FIELD',
    },
    {
      id: 'businessHoursIn',
      arangoId: 'Variables/businessHoursIn',
      name: 'Entry access schedule',
      description: 'Opening time of the cenote',
      units: null,
      timeseries: false,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.109+00:00',
      type: 'TIME',
      enumValues: null,
      accessLevel: 'PUBLIC',
      theme: 'TOURISM',
      origin: 'FIELD',
    },
    {
      id: 'businessHoursOut',
      arangoId: 'Variables/businessHoursOut',
      name: 'Exit access schedule',
      description: 'Closing time of the cenote',
      units: null,
      timeseries: false,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.112+00:00',
      type: 'TIME',
      enumValues: null,
      accessLevel: 'PUBLIC',
      theme: 'TOURISM',
      origin: 'FIELD',
    },
    {
      id: 'cabinsRooms',
      arangoId: 'Variables/cabinsRooms',
      name: 'Cabins or rooms',
      description: 'Installed facilities for the lodging of visitors',
      units: null,
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.114+00:00',
      type: 'BOOLEAN',
      enumValues: null,
      accessLevel: 'PUBLIC',
      theme: 'TOURISM',
      origin: 'FIELD',
    },
    {
      id: 'cadmium',
      arangoId: 'Variables/cadmium',
      name: 'Cadmium',
      description: 'Amount of Cadmium in cenote water',
      units: 'mg/g',
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.117+00:00',
      type: 'NUMBER_WITH_UNITS',
      enumValues: null,
      accessLevel: 'SENSITIVE',
      theme: 'WATER',
      origin: 'OFFICE',
    },
    {
      id: 'caffeine',
      arangoId: 'Variables/caffeine',
      name: 'Caffeine',
      description: 'Amount of caffeine in cenote water',
      units: 'ng/L',
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.119+00:00',
      type: 'NUMBER_WITH_UNITS',
      enumValues: null,
      accessLevel: 'SENSITIVE',
      theme: 'WATER',
      origin: 'OFFICE',
    },
    {
      id: 'calcium',
      arangoId: 'Variables/calcium',
      name: 'Calcium',
      description: 'Amount of Calcium in cenote water',
      units: 'mg/g',
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.122+00:00',
      type: 'NUMBER_WITH_UNITS',
      enumValues: null,
      accessLevel: 'SENSITIVE',
      theme: 'WATER',
      origin: 'OFFICE',
    },
    {
      id: 'camping',
      arangoId: 'Variables/camping',
      name: 'Camping area',
      description: 'Possibility of camping or spending the night outdoors',
      units: null,
      timeseries: false,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.124+00:00',
      type: 'BOOLEAN',
      enumValues: null,
      accessLevel: 'PUBLIC',
      theme: 'TOURISM',
      origin: 'FIELD',
    },
    {
      id: 'cancunAccess',
      arangoId: 'Variables/cancunAccess',
      name: 'Accessibility classification from Cancun',
      description:
        'Scale from 1 to 4 of the degree of accessibility to the cenote from Cancun',
      units: null,
      timeseries: false,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.127+00:00',
      type: 'UNITLESS_NUMBER',
      enumValues: null,
      accessLevel: 'PRIVATE',
      theme: 'GEOREFERENCE',
      origin: 'OFFICE',
    },
    {
      id: 'cancunDistance',
      arangoId: 'Variables/cancunDistance',
      name: 'Distance from Cancun',
      description: 'Approximate distance between Cancun and the cenote',
      units: 'km',
      timeseries: false,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.130+00:00',
      type: 'NUMBER_WITH_UNITS',
      enumValues: null,
      accessLevel: 'PRIVATE',
      theme: 'GEOREFERENCE',
      origin: 'OFFICE',
    },
    {
      id: 'cancunSpeed',
      arangoId: 'Variables/cancunSpeed',
      name: 'Speed Cancun (Km / hr)',
      description:
        'Calculation of the average crossing speed between the cenote and the city of Cancun',
      units: 'Km/h',
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.133+00:00',
      type: 'NUMBER_WITH_UNITS',
      enumValues: null,
      accessLevel: 'PRIVATE',
      theme: 'GEOREFERENCE',
      origin: 'OFFICE',
    },
    {
      id: 'cancunTime',
      arangoId: 'Variables/cancunTime',
      name: 'Total Time to Cancun',
      description:
        'Vehicle travel time plus time on foot from Cancun to the cenote',
      units: 'h',
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.136+00:00',
      type: 'NUMBER_WITH_UNITS',
      enumValues: null,
      accessLevel: 'PUBLIC',
      theme: 'GEOREFERENCE',
      origin: 'OFFICE',
    },
    {
      id: 'carbonates',
      arangoId: 'Variables/carbonates',
      name: 'Carbonates',
      description: 'Amount of carbonates in cenote water',
      units: '%',
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.138+00:00',
      type: 'NUMBER_WITH_UNITS',
      enumValues: null,
      accessLevel: 'SENSITIVE',
      theme: 'WATER',
      origin: 'OFFICE',
    },
    {
      id: 'carboxylesterase',
      arangoId: 'Variables/carboxylesterase',
      name: 'Carboxylesterase',
      description: 'Amount of Carboxylesterase in cenote water',
      units: 'U/mg proteina',
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.141+00:00',
      type: 'NUMBER_WITH_UNITS',
      enumValues: null,
      accessLevel: 'SENSITIVE',
      theme: 'WATER',
      origin: 'OFFICE',
    },
    {
      id: 'cardPayment',
      arangoId: 'Variables/cardPayment',
      name: 'Payment by credit card',
      description:
        'Possibility of paying for the service with a credit or debit card',
      units: null,
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.144+00:00',
      type: 'BOOLEAN',
      enumValues: null,
      accessLevel: 'PUBLIC',
      theme: 'TOURISM',
      origin: 'FIELD',
    },
    {
      id: 'catalase',
      arangoId: 'Variables/catalase',
      name: 'Catalase',
      description: 'Amount of Catalase in cenote water',
      units: 'U/mg proteina',
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.147+00:00',
      type: 'NUMBER_WITH_UNITS',
      enumValues: null,
      accessLevel: 'SENSITIVE',
      theme: 'WATER',
      origin: 'OFFICE',
    },
    {
      id: 'cautionSigns',
      arangoId: 'Variables/cautionSigns',
      name: 'Caution signs, signage',
      description:
        'Informative signs for the address, location and effective flow of people',
      units: null,
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.149+00:00',
      type: 'BOOLEAN',
      enumValues: null,
      accessLevel: 'PRIVATE',
      theme: 'ORGANIZATION',
      origin: 'FIELD',
    },
    {
      id: 'cellRedoxPotential',
      arangoId: 'Variables/cellRedoxPotential',
      name: 'Cellular redox potential',
      description: 'Amount of cellular redox potential in cenote water',
      units: 'mV',
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.152+00:00',
      type: 'NUMBER_WITH_UNITS',
      enumValues: null,
      accessLevel: 'SENSITIVE',
      theme: 'WATER',
      origin: 'OFFICE',
    },
    {
      id: 'cenRoadsigns',
      arangoId: 'Variables/cenRoadsigns',
      name: 'Advertisements or roadside signs',
      description: 'Propaganda located on roads announcing to the cenote',
      units: null,
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.155+00:00',
      type: 'BOOLEAN',
      enumValues: null,
      accessLevel: 'PRIVATE',
      theme: 'ORGANIZATION',
      origin: 'FIELD',
    },
    {
      id: 'cenoteLights',
      arangoId: 'Variables/cenoteLights',
      name: 'Electrical lighting inside cenote',
      description: 'Presence of artificial lightings inside the cenote',
      units: null,
      timeseries: true,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.157+00:00',
      type: 'BOOLEAN',
      enumValues: null,
      accessLevel: 'PRIVATE',
      theme: 'ORGANIZATION',
      origin: 'FIELD',
    },
    {
      id: 'ceramics',
      arangoId: 'Variables/ceramics',
      name: 'Ceramics Items',
      description: 'Presence of ceramic articles or ceramic remains',
      units: null,
      timeseries: false,
      multiple: false,
      methodology: null,
      createdAt: '2021-09-30T01:23:13.740+00:00',
      updatedAt: '2022-03-16T15:05:46.160+00:00',
      type: 'BOOLEAN',
      enumValues: null,
      accessLevel: 'SENSITIVE',
      theme: 'CULTURAL',
      origin: 'FIELD',
    },
  ],
  pageable: {
    sort: { empty: true, sorted: false, unsorted: true },
    offset: 30,
    pageNumber: 1,
    pageSize: 30,
    unpaged: false,
    paged: true,
  },
  last: false,
  totalPages: 10,
  totalElements: 286,
  size: 30,
  number: 1,
  sort: { empty: true, sorted: false, unsorted: true },
  first: false,
  numberOfElements: 30,
  empty: false,
};
