name: Deploy to Firebase Hosting

# on:
#   push:
#     branches:
#       - main
on:
  pull_request:
    branches:
      - '*'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js and pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install Firebase CLI
        run: pnpm install -g firebase-tools

      - name: Install dependencies
        run: pnpm install

      - name: Login to Firebase
        run: firebase login:ci
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Build your app
        run: pnpm deploy:site
